import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CommingSoonLayout from "@/components/comming-soon-layout/comming-soon-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <main
          style={{
            fontFamily: "Arial, sans-serif",
            backgroundColor: "#f5f5f5",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
            margin: 0,
          }}
        >
          <CommingSoonLayout />
        </main>
      </body>
    </html>
  );
}
